In [6]:
!pip install pandas
!pip install scikit-learn



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\sande\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
    --------------------------------------- 0.3/11.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.1 MB 1.3 MB/s eta 0:00:09
   --- ------------------------------------ 1.0/11.1 MB 1.7 MB/s eta 0:00:07
   ------ --------------------------------- 1.8/11.1 MB 2.3 MB/s eta 0:00:04
   --------- ------------------------------ 2.6/11.1 MB 2.7 MB/s eta 0:00:04
   ------------ --------------------------- 3.4/11.1 MB 2.8 MB/s eta 0:00:03
   --------------- ------------------------ 4.2/11.1 MB 3.0 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.1 MB 3.1 MB/s eta 0:00:03
   -------------------- ------------------- 5.8/11.1 MB 3.2 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.1 MB 3.2 MB/s eta 0:00:02
   ------------------------- -------------- 7.1/11.1 MB 3.2 MB/s eta 0:00:02
   -----------------


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: C:\Users\sande\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA

data_path = 'pca.csv'
bp_data = pd.read_csv(data_path)
print(bp_data)
print()

features = bp_data.iloc[:, :-1].values
labels = bp_data.iloc[:, -1].values

encoder = LabelEncoder()
encoded_labels = encoder.fit_transform(labels)

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

pca = PCA(n_components=2)
reduced_features = pca.fit_transform(scaled_features)

X_train, X_test, y_train, y_test = train_test_split(reduced_features, encoded_labels, test_size=0.3, random_state=42)

def test_knn(X_train, X_test, y_train, y_test, neighbors_list, weighted=False):
    output_metrics = {}
    max_k = len(X_train)
    for neighbors in neighbors_list:
        if neighbors > max_k:
            continue
        model = KNeighborsClassifier(n_neighbors=neighbors, weights='distance' if weighted else 'uniform')
        model.fit(X_train, y_train)
        predictions = model.predict(X_test)
        acc = accuracy_score(y_test, predictions)
        f1 = f1_score(y_test, predictions, average='weighted')
        matrix = confusion_matrix(y_test, predictions)
        output_metrics[neighbors] = {'accuracy': acc, 'f1_score': f1, 'conf_matrix': matrix}
    return output_metrics

neighbors_list = [1, 3, 5]

normal_knn = test_knn(X_train, X_test, y_train, y_test, neighbors_list, weighted=False)
print("Regular k-NN Results:")
for k, results in normal_knn.items():
    print(f"\nk = {k} | Accuracy = {results['accuracy']:.4f} | F1 Score = {results['f1_score']:.4f}")
    print("Confusion Matrix:")
    print(results['conf_matrix'])

weighted_knn = test_knn(X_train, X_test, y_train, y_test, neighbors_list, weighted=True)
print("\nDistance-Weighted k-NN Results:")
for k, results in weighted_knn.items():
    print(f"\nk = {k} | Accuracy = {results['accuracy']:.4f} | F1 Score = {results['f1_score']:.4f}")
    print("Confusion Matrix:")
    print(results['conf_matrix'])


   sys_bp  dis_bp      label
0     126      78     normal
1     128      80     normal
2     128      82  evaluated
3     130      82  evaluated
4     130      84       high
5     132      86       high

Regular k-NN Results:

k = 1 | Accuracy = 0.0000 | F1 Score = 0.0000
Confusion Matrix:
[[0 0]
 [2 0]]

k = 3 | Accuracy = 0.0000 | F1 Score = 0.0000
Confusion Matrix:
[[0 0]
 [2 0]]

Distance-Weighted k-NN Results:

k = 1 | Accuracy = 0.0000 | F1 Score = 0.0000
Confusion Matrix:
[[0 0]
 [2 0]]

k = 3 | Accuracy = 0.0000 | F1 Score = 0.0000
Confusion Matrix:
[[0 0]
 [2 0]]
